# Generated by Django 5.0.2 on 2024-02-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_fleets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fleets',
        ),
    ]
