// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2nJJ0QAZKKB8VI_7k7bM5wf-8Nosq8zo',
    appId: '1:131643657404:web:507b07d1a6fdf4cebd94b9',
    messagingSenderId: '131643657404',
    projectId: 'optiz-ffcf9',
    authDomain: 'optiz-ffcf9.firebaseapp.com',
    storageBucket: 'optiz-ffcf9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvTh784M_KrbLveVZF6O7vvxvFlKqdlxY',
    appId: '1:131643657404:android:7a9e1feba4df6014bd94b9',
    messagingSenderId: '131643657404',
    projectId: 'optiz-ffcf9',
    storageBucket: 'optiz-ffcf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Vd8AO6VwAI_nRpNJ5N-hzlhroyFtPUU',
    appId: '1:131643657404:ios:377dda637c85e359bd94b9',
    messagingSenderId: '131643657404',
    projectId: 'optiz-ffcf9',
    storageBucket: 'optiz-ffcf9.appspot.com',
    iosBundleId: 'com.example.optiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Vd8AO6VwAI_nRpNJ5N-hzlhroyFtPUU',
    appId: '1:131643657404:ios:137cc78f66c28b07bd94b9',
    messagingSenderId: '131643657404',
    projectId: 'optiz-ffcf9',
    storageBucket: 'optiz-ffcf9.appspot.com',
    iosBundleId: 'com.example.optiz.RunnerTests',
  );
}
