# Generated by Django 2.1.7 on 2019-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('present', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('present', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=None)),
                ('email', models.EmailField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('status', models.CharField(default='Absent', max_length=10)),
                ('time', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
