# Generated by Django 2.1.7 on 2019-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
