# Generated by Django 2.1.7 on 2019-03-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190320_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
